### ISSUE TITLE
Submit packages to Tumbleweed

### ISSUE THREAD

**Issue by Martchus** [Martchus/syncthingtray#12]
* Submit [existing packages](https://build.opensuse.org/project/show/home:mkittler) to Tumbleweed
* Note: This also covers my other projects and required dependencies.

## TODOs and checklist

1. Find appropriate devel projects:
    * [x] [c++utilities](https://github.com/Martchus/cpp-utilities): devel:libraries:c_c++
    * [x] [qtutilities](https://github.com/Martchus/qtutilities): devel:libraries:c_c++ (not sure, especially because it depends on Qt)
    * [x] [qtforkawesome](https://github.com/Martchus/qtforkawesome): devel:libraries:c_c++ (not sure, especially because it depends on Qt)
    * [x] [syncthingtray](https://github.com/Martchus/syncthingtray): network (makes sense because syncthing and qsyncthingtray are already there)
    * [x] [tagparser](https://github.com/Martchus/tagparser): multimedia:libs (makes sense because taglib is already there)
    * [x] [tageditor](https://github.com/Martchus/tageditor): multimedia:apps (makes sense because kid3 is already there)
    * [ ] [passwordfile](https://github.com/Martchus/passwordfile): maybe devel:libraries:c_c++
    * [ ] [passwordmanager](https://github.com/Martchus/passwordmanager)
    * [x] [reflective-rapidjson](https://github.com/Martchus/reflective-rapidjson): devel:libraries:c_c++
2. Submit packages to those projects: https://en.opensuse.org/openSUSE:How_to_contribute_to_Factory#How_to_add_a_new_package_to_Factory
    * [x] c++utilities: https://build.opensuse.org/request/show/561469
    * [ ] qtutilities: https://build.opensuse.org/request/show/562790
    * [ ] qtforkawesome
    * [ ] syncthingtray: https://build.opensuse.org/request/show/562793
    * [ ] tagparser: https://build.opensuse.org/request/show/562791
    * [ ] tageditor: https://build.opensuse.org/request/show/562792
3. Fix issues
    * [ ] c++utilities
        * [x] rename library or ignore that issue for now (name must be less generic)
            * ignored
        * [ ] s/soname/sover/
        * [ ] <s>inline reponame, since that doesn't change</s> convince people to use variable names for repo
            * not gonna happen, I'd like to have common code as much generic as possible
        * [x] require gcc5-c++ instead of gcc >= 5 (use CXX=/usr/bin/g++-5 in Leap)
        * [x] fix service files (need to figure out alternative)
        * [x] use CMake macro (need to figure out how those work)
    * [ ] qtutilities
        * [ ] rename library or ignore that issue for now (name must be less generic)
        * [ ] s/soname/sover/
        * [ ] <s>inline reponame, since that doesn't change</s> convince people to use variable names for repo
            * not gonna happen, I'd like to have common code as much generic as possible
        * [x] require gcc5-c++ instead of gcc >= 5 (use CXX=/usr/bin/g++-5 in Leap)
        * [x] fix service files (need to figure out alternative)
        * [x] use CMake macro (need to figure out how those work)
    * [ ] qtforkawesome
        * [ ] using ForkAwesome sources directly is maybe not accepted
    * [x] syncthingtray
        * [x] require gcc5-c++ instead of gcc >= 5 (use CXX=/usr/bin/g++-5 in Leap)
        * [x] fix service files (need to figure out alternative)
        * [x] use CMake macro (need to figure out how those work)
    * [ ] tagparser
        * [ ] fix naming (I do not really know what is meant by that)
        * [x] require gcc5-c++ instead of gcc >= 5 (use CXX=/usr/bin/g++-5 in Leap)
        * [x] fix service files (need to figure out alternative)
        * [x] use CMake macro (need to figure out how those work)
    * [x] tageditor
        * [x] require gcc5-c++ instead of gcc >= 5 (use CXX=/usr/bin/g++-5 in Leap)
        * [x] fix service files (need to figure out alternative)
        * [x] use CMake macro (need to figure out how those work)
    * [x] [passwordfile](https://github.com/Martchus/passwordfile)
        * [x] require gcc5-c++ instead of gcc >= 5 (use CXX=/usr/bin/g++-5 in Leap)
        * [x] fix service files (need to figure out alternative)
        * [x] use CMake macro (need to figure out how those work)
    * [x] [passwordmanager](https://github.com/Martchus/passwordmanager)
        * [x] require gcc5-c++ instead of gcc >= 5 (use CXX=/usr/bin/g++-5 in Leap)
        * [x] fix service files (need to figure out alternative)
        * [x] use CMake macro (need to figure out how those work)
    * [x] [reflective-rapidjson](https://github.com/Martchus/reflective-rapidjson)
        * [x] require gcc5-c++ instead of gcc >= 5 (use CXX=/usr/bin/g++-5 in Leap)
        * [x] fix service files (need to figure out alternative)
        * [x] use CMake macro (need to figure out how those work)
4. Submit packages to factory: `osc submitrequest develproj/package openSUSE:Factory`
    * [ ] c++utilities
    * [ ] qtutilities
    * [ ] qtforkawesome
    * [ ] syncthingtray
    * [ ] tagparser
    * [ ] tageditor
    * [ ] passwordfile
    * [ ] passwordmanager
    * [ ] reflective-rapidjson
---

@lbeltrame FYI, since you liked to have the package in Tumbleweed.

**Comment by Martchus** [comment]
My home project must be good for now. So I'll close this until I decide to work on it again.
